name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - boto3=1.28.50
  - click=8.1.7
  - dask=2024.2.1
  - distributed=2024.2.1
  - fiona=1.9.4
  - flask=2.3.3
  - flask-restful=0.3.10
  - geopandas=0.14.0
  - netcdf4=1.6.4
  - pymongo=4.5.0
  - pyshp=2.3.1
  - requests=2.31.0
  - s3fs
  - shapely=2.0.1
  - xarray=2024.2.0
  - zarr=2.16.1
  - uwsgi
  - gdal